/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.mybank;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class AddAccountMenu extends javax.swing.JDialog {

    /**
     * Creates new form AddAccountMenu
     */
    public AddAccountMenu(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        firstNameButton = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameButton = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        ssnButton = new javax.swing.JLabel();
        ssnField = new javax.swing.JTextField();
        depositButton = new javax.swing.JLabel();
        depositField = new javax.swing.JTextField();
        balanceButton = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account");
        getContentPane().setLayout(new java.awt.GridLayout(6, 2, 5, 5));

        firstNameButton.setText("First Name");
        getContentPane().add(firstNameButton);
        getContentPane().add(firstNameField);

        lastNameButton.setText("last name");
        getContentPane().add(lastNameButton);
        getContentPane().add(lastNameField);

        ssnButton.setText("Social Security Number");
        getContentPane().add(ssnButton);
        getContentPane().add(ssnField);

        depositButton.setText("Initial Deposit");
        getContentPane().add(depositButton);
        getContentPane().add(depositField);

        balanceButton.setText("Account Type");
        getContentPane().add(balanceButton);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Savings", "Loan", "Current", "Checkings", " " }));
        getContentPane().add(jComboBox1);

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });
        getContentPane().add(okButton);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(cancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        StringBuilder warnings = new StringBuilder();
        String firstName = "", lastName = "", ssn = "", depositString = "";
        double amount = 0;
        //Verify first name field
        if (firstNameField.getText().isEmpty()) {
            warnings.append("First name must not be empty.\n");
        } else {
            firstName = firstNameField.getText();
        }
        //Verify last name field
        if (lastNameField.getText().isEmpty()) {
            warnings.append("Last name must not be empty.\n");
        } else {
            lastName = lastNameField.getText();
        }
        if (!ssnField.getText().matches("(\\d{3}-?){2}\\d{4}")) {
            warnings.append("SSN must be 9 digits, dashes are acceptable.\n");
        } else {
            ssn = ssnField.getText().replace("-", "");
        }
        //Verify initial deposit
        if (depositField.getText().isEmpty()) {
            warnings.append("Initial deposit must be entered.");
        }
         else {
            try {
                amount = Double.parseDouble(depositField.getText());
            } catch (NumberFormatException ex) {
                warnings.append("Initial deposit must be a number.");
            }
        }
        if (warnings.length() > 0) {
            JOptionPane.showMessageDialog(this, warnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
        } else {
            Account account = null;
            if (jComboBox1.getSelectedItem().toString().equals("Checking")) {
                if (amount >= 100) {
                    account = new Checking(amount);
                } else {
                    warnings.append("Initial deposit must be at least $100 for Checking accounts.");
                }
            } else if (jComboBox1.getSelectedItem().toString().equals("Savings")) {
                if (amount >= 50) {
                    account = new Savings(amount);
                } else {
                    warnings.append("Initial deposit must be at least $50 for Savings accounts.");
                }
            }
            if (account != null) {
                Customer customer = new Customer(firstName, lastName, ssn, account);
                bank.addCustomer(customer);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, warnings.toString(), "Input Warnings", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
       this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel balanceButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel depositButton;
    private javax.swing.JTextField depositField;
    private javax.swing.JLabel firstNameButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel lastNameButton;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel ssnButton;
    private javax.swing.JTextField ssnField;
    // End of variables declaration//GEN-END:variables

    Object getCustomer() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
